name: Daily Savings Bot

on:
  workflow_dispatch:  # manual run
  schedule:
    - cron: '0 16 * * *'  # 7 PM Kenya time = 16:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2'

      - name: Install R packages
        run: |
          R -e "install.packages('remotes')"
          R -e "remotes::install_cran(c(
            'dplyr','lubridate','rvest','httr','stringr','ggplot2','tidyr','patchwork','scales','telegram.bot',
            'googlesheets4','gargle', 'base64enc'
          ))"


      - name: Write Google credentials
        run: |
          echo "${{ env.GSHEET_JSON_B64 }}" | base64 --decode > gs.json
          chmod 600 gs.json
          
      - name: Test libraries
        run: |
          R -e "library(googlesheets4); library(dplyr); library(ggplot2); print('Packages loaded successfully')"

      - name: Run Daily Savings Bot
        run: Rscript daily_savings_bot.R
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GSHEET_JSON_B64: ${{ secrets.GSHEET_JSON_B64 }}
          YOUR_GOOGLE_SHEET_URL: ${{ secrets.YOUR_GOOGLE_SHEET_URL }}
          SHEET_URL_Z: ${{ secrets.SHEET_URL_Z }}

